using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using WRLDZ.Duel.TextEffects;

namespace WRLDZ.Duel
{
    /// <summary>
    /// Simple one-shot trap/QE timings mined from YGOPro Lua for cards in
    /// <c>cards_db.json</c>. Facts only — we do not run Lua.
    /// Regenerated by <c>Tools/extract_ygopro_triggers.py</c>.
    /// </summary>
    public static class YgoProTriggerCatalog
    {
        const string SeedFile = "ygopro_trigger_seed_v1.json";

        [Serializable]
        public class TriggerFact
        {
            public int cardId;
            public string timing;
            public string action;
            public int amount;
            public int lpMultiple;
            public bool alsoDef;
            public string requiresControllerRace;
            public bool opponentTurn;
        }

        [Serializable]
        class SeedDto
        {
            public int triggerCount;
            public TriggerFact[] triggers;
        }

        static bool _loaded;
        static readonly Dictionary<int, TriggerFact> ById = new();

        public static int Count { get; private set; }

        public static void EnsureLoaded()
        {
            if (_loaded) return;
            _loaded = true;
            var path = Path.Combine(Application.streamingAssetsPath, "WRLDZ", SeedFile);
            if (!File.Exists(path))
            {
                Debug.LogWarning("[WRLDZ] YGOPro trigger seed missing: " + path);
                return;
            }

            try
            {
                var dto = JsonUtility.FromJson<SeedDto>(File.ReadAllText(path));
                if (dto?.triggers == null) return;
                foreach (var t in dto.triggers)
                {
                    if (t == null || t.cardId <= 0) continue;
                    ById[t.cardId] = t;
                }

                Count = ById.Count;
                Debug.Log($"[WRLDZ] YGOPro trigger catalog: {Count} one-shot traps/QEs.");
            }
            catch (Exception ex)
            {
                Debug.LogWarning("[WRLDZ] YGOPro trigger seed parse failed: " + ex.Message);
            }
        }

        public static TriggerFact For(int cardId)
        {
            EnsureLoaded();
            return ById.TryGetValue(cardId, out var t) ? t : null;
        }

        public static bool IsLegal(DuelEngine engine, DuelistState who, CardInstance card,
            ResponseTiming timing)
        {
            var fact = For(card != null ? card.CardId : 0);
            if (fact == null) return false;
            if (!TimingMatches(fact.timing, timing)) return false;
            if (fact.opponentTurn && engine.TurnPlayer == who) return false;
            if (!string.IsNullOrEmpty(fact.requiresControllerRace) &&
                !ControllerHasBattlingRace(engine, who, fact.requiresControllerRace))
                return false;
            if (fact.lpMultiple > 0 && who.LifePoints < fact.lpMultiple)
                return false;
            if (fact.action == "lose_atk_def_pay_lp" || fact.action == "lose_atk_eot")
            {
                var oppMon = OpponentBattlingMonster(engine, who);
                if (oppMon == null || !oppMon.FaceUp) return false;
                if (fact.lpMultiple > 0 &&
                    oppMon.CurrentAtk < fact.lpMultiple && oppMon.CurrentDef < fact.lpMultiple)
                    return false;
            }

            if (fact.action == "destroy_summoned")
            {
                var summoned = engine.PendingResponse?.Summoned;
                if (summoned == null || summoned.CurrentAtk < Math.Max(1, fact.amount))
                    return false;
            }

            return true;
        }

        public static bool TryResolve(DuelEngine engine, DuelistState who, CardInstance card,
            bool autoPick)
        {
            var fact = For(card != null ? card.CardId : 0);
            if (fact == null || engine == null || who == null) return false;
            if (!IsLegal(engine, who, card, engine.PendingResponse?.Timing ?? ResponseTiming.None) &&
                engine.PendingResponse != null)
                return false;

            if (fact.action == "lose_atk_def_pay_lp")
            {
                var target = OpponentBattlingMonster(engine, who);
                var choices = LpChoices(who, target, fact.lpMultiple);
                if (choices.Count == 0) return false;
                SpellTrapEffects.PlaceFaceUpForActivation(engine, who, card, fromHand: false);
                engine.Log($"Activate: {card.Name}.");
                if (autoPick || !who.IsPlayer)
                {
                    ApplyPayLpLoss(engine, who, card, target, choices[choices.Count - 1], fact.alsoDef);
                    return true;
                }

                var pending = new PendingActivation
                {
                    Controller = who,
                    Card = card,
                    FromHand = false,
                    WasSetOnField = true,
                    AwaitingLpCost = true,
                    ResumeDamageCalculation = true,
                    LockedTarget = target,
                    AlsoAffectsDef = fact.alsoDef
                };
                pending.LpCostChoices.AddRange(choices);
                engine.ClearPendingResponse();
                engine.SetPendingActivation(pending);
                engine.Log($"{card.Name}: pay LP in multiples of {fact.lpMultiple} (cost).");
                engine.NotifyPublic();
                return true;
            }

            SpellTrapEffects.PlaceFaceUpForActivation(engine, who, card, fromHand: false);
            engine.Log($"Activate: {card.Name}.");
            var attackNegated = false;
            var battleEnded = false;
            Execute(engine, who, card, fact, ref attackNegated, ref battleEnded);
            SpellTrapEffects.FinishCardPublic(engine, who, card, staysOnField: false);
            engine.ContinueAfterResponseActivation(attackNegated, battleEnded);
            return true;
        }

        public static bool FinishPayLp(DuelEngine engine, int amount)
        {
            var p = engine?.PendingActivation;
            if (p == null || !p.AwaitingLpCost) return false;
            if (!p.LpCostChoices.Contains(amount)) return false;
            var who = p.Controller;
            var card = p.Card;
            var target = p.LockedTarget;
            engine.ClearPendingActivation();
            ApplyPayLpLoss(engine, who, card, target, amount, p.AlsoAffectsDef);
            return true;
        }

        static void ApplyPayLpLoss(DuelEngine engine, DuelistState who, CardInstance card,
            CardInstance target, int amount, bool alsoDef)
        {
            who.LifePoints = Math.Max(0, who.LifePoints - amount);
            engine.Log($"Cost: pay {amount} LP → {who.Name} at {who.LifePoints} LP.");
            if (target != null)
            {
                if (ContinuousProtections.TargetedEffectBlocked(engine, target, card)) {
                    engine.Log("Target is protected at resolution.");
                    SpellTrapEffects.FinishCardPublic(engine, who, card, staysOnField: false);
                    engine.ContinueAfterResponseActivation(false, false);
                    return;
                }
                target.UntilEndOfTurnAtk -= amount;
                if (alsoDef) target.UntilEndOfTurnDef -= amount;
                engine.Log(
                    $"{target.Name} loses {amount} ATK" +
                    (alsoDef ? $"/{amount} DEF" : "") +
                    $" until the End Phase (now {target.CurrentAtk}/{target.CurrentDef}).");
            }

            SpellTrapEffects.FinishCardPublic(engine, who, card, staysOnField: false);
            engine.ContinueAfterResponseActivation(false, false);
        }

        static void Execute(DuelEngine engine, DuelistState who, CardInstance card, TriggerFact fact,
            ref bool attackNegated, ref bool battleEnded)
        {
            engine.TryGetBattlingPair(out var attacker, out _);
            var opp = engine.OpponentOf(who);
            switch (fact.action)
            {
                case "destroy_attacker":
                    if (attacker != null)
                    {
                        if (ContinuousProtections.TargetedEffectBlocked(engine, attacker, card)) {
                            engine.Log("Target is protected at resolution.");
                            break;
                        }
                        engine.DestroyMonsterPublic(engine.ControllerOf(attacker) ?? opp, attacker);
                        attackNegated = true;
                    }

                    break;
                case "destroy_opp_atk_pos":
                    foreach (var m in new List<CardInstance>(opp.MonstersOnField()))
                    {
                        if (m != null && m.FaceUp && m.Position == BattlePosition.Attack)
                        {
                            if (m == attacker) attackNegated = true;
                            engine.DestroyMonsterPublic(opp, m);
                        }
                    }

                    break;
                case "negate_attack_end_bp":
                    engine.Log("Attack negated — Battle Phase ends.");
                    if (engine.DeclaredAttackingPlayer != null)
                        engine.ForceEndBattlePhase(engine.DeclaredAttackingPlayer);
                    else if (engine.TurnPlayer != null)
                        engine.ForceEndBattlePhase(engine.TurnPlayer);
                    attackNegated = true;
                    battleEnded = true;
                    break;
                case "negate_this_attack":
                case "negate_attack_damage":
                case "negate_attack_gain_lp":
                    if (fact.action != "negate_this_attack" &&
                        ContinuousProtections.TargetedEffectBlocked(engine, attacker, card)) {
                        engine.Log("Target is protected at resolution.");
                        break;
                    }

                    engine.Log("Attack negated.");
                    attackNegated = true;
                    if (fact.action == "negate_attack_damage" && attacker != null)
                        engine.ApplyEffectDamage(opp, attacker.CurrentAtk, card.Name);
                    if (fact.action == "negate_attack_gain_lp" && attacker != null)
                    {
                        TextEffectRuntime.ApplyLifePointGain(engine, who, attacker.CurrentAtk, card?.Name);
                    }

                    break;
                case "banish_opp_def_pos":
                    foreach (var m in new List<CardInstance>(opp.MonstersOnField()))
                    {
                        if (m != null && m.Position == BattlePosition.Defense)
                            engine.BanishCard(opp, m);
                    }

                    attackNegated = false;
                    break;
                case "lose_atk_eot":
                    if (attacker != null)
                    {
                        if (ContinuousProtections.TargetedEffectBlocked(engine, attacker, card)) {
                            engine.Log("Target is protected at resolution.");
                            break;
                        }
                        attacker.UntilEndOfTurnAtk -= Math.Max(0, fact.amount);
                        engine.Log(
                            $"{attacker.Name} loses {fact.amount} ATK until the End Phase " +
                            $"(now {attacker.CurrentAtk}).");
                    }

                    break;
                case "destroy_summoned":
                {
                    var summoned = engine.PendingResponse?.Summoned;
                    var summoner = engine.PendingResponse?.Summoner;
                    if (summoned != null && summoner != null &&
                        summoned.CurrentAtk >= Math.Max(1, fact.amount))
                    {
                        if (ContinuousProtections.TargetedEffectBlocked(engine, summoned, card)) {
                            engine.Log("Target is protected at resolution.");
                            break;
                        }
                        engine.DestroyMonsterPublic(summoner, summoned);
                    }
                    break;
                }
            }
        }

        public static bool TimingMatches(string factTiming, ResponseTiming timing)
        {
            if (string.IsNullOrEmpty(factTiming)) return false;
            if (factTiming == "attack_announce") return timing == ResponseTiming.AttackDeclared;
            if (factTiming == "damage_step") return timing == ResponseTiming.DamageCalculation;
            if (factTiming == "summon_success") return timing == ResponseTiming.MonsterSummoned;
            return false;
        }

        public static bool ControllerHasBattlingRace(DuelEngine engine, DuelistState who, string race)
        {
            if (engine == null || who == null || string.IsNullOrEmpty(race)) return false;
            if (!engine.TryGetBattlingPair(out var attacker, out var target)) return false;
            return IsControlledRace(who, attacker, race) || IsControlledRace(who, target, race);
        }

        public static CardInstance OpponentBattlingMonster(DuelEngine engine, DuelistState who)
        {
            if (!engine.TryGetBattlingPair(out var attacker, out var target)) return null;
            var opp = engine.OpponentOf(who);
            if (attacker != null && opp != null && opp.TryFindMonster(attacker, out _))
                return attacker;
            if (target != null && opp != null && opp.TryFindMonster(target, out _))
                return target;
            return null;
        }

        static bool IsControlledRace(DuelistState who, CardInstance m, string race)
        {
            if (m == null || !m.FaceUp || m.Def == null) return false;
            if (!who.TryFindMonster(m, out _)) return false;
            return string.Equals(m.Def.race, race, StringComparison.OrdinalIgnoreCase);
        }

        public static List<int> LpChoices(DuelistState who, CardInstance target, int multiple)
        {
            var list = new List<int>();
            if (who == null || multiple <= 0) return list;
            var cap = who.LifePoints;
            if (target != null)
            {
                var stat = Math.Max(target.CurrentAtk, target.CurrentDef);
                if (stat < cap) cap = stat;
            }

            cap = cap / multiple * multiple;
            for (var n = multiple; n <= cap; n += multiple)
                list.Add(n);
            return list;
        }
    }
}
