using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace WRLDZ.Duel
{
    /// <summary>
    /// Bulk continuous effects mined from local YGOPro / EDOPro Lua
    /// (<c>~/ygopro-scripts</c>, Project Ignis official). Facts only — we do not
    /// run Lua. Regenerated by <c>Tools/extract_ygopro_continuous.py</c>.
    /// Numeric field ATK/DEF auras + simple DIRECT_ATTACK and EXTRA_ATTACK grants.
    /// </summary>
    public static class YgoProContinuousCatalog
    {
        const string SeedFile = "ygopro_continuous_seed_v1.json";

        [Serializable]
        public class Aura
        {
            public int cardId;
            public int atk;
            public int def;
            public string attribute;
            public string race;
            public bool selfOnly;
            public bool controllerOnly;
            public bool opponentOnly;
            public string sourceZone;
        }

        [Serializable]
        public class DirectGrant
        {
            public int cardId;
            public string requiresName;
        }

        [Serializable]
        public class ExtraAttackGrant
        {
            public int cardId;
            /// <summary>YGOPro SetValue — extra attacks (1 = attack twice).</summary>
            public int extra;
            public string requiresName;
        }

        [Serializable]
        class SeedFileDto
        {
            public string source;
            public int scriptFiles;
            public int auraCount;
            public int directCount;
            public int extraCount;
            public Aura[] auras;
            public DirectGrant[] directAttacks;
            public ExtraAttackGrant[] extraAttacks;
        }

        static bool _loaded;
        static readonly Dictionary<int, List<Aura>> AurasById = new();
        static readonly Dictionary<int, List<DirectGrant>> DirectsById = new();
        static readonly Dictionary<int, List<ExtraAttackGrant>> ExtraById = new();

        public static int AuraCardCount { get; private set; }
        public static int DirectCardCount { get; private set; }
        public static int ExtraAttackCardCount { get; private set; }

        public static void EnsureLoaded()
        {
            if (_loaded) return;
            _loaded = true;
            var path = Path.Combine(Application.streamingAssetsPath, "WRLDZ", SeedFile);
            if (!File.Exists(path))
            {
                Debug.LogWarning("[WRLDZ] YGOPro continuous seed missing: " + path);
                return;
            }

            try
            {
                var dto = JsonUtility.FromJson<SeedFileDto>(File.ReadAllText(path));
                if (dto?.auras != null)
                {
                    foreach (var a in dto.auras)
                    {
                        if (a == null || a.cardId <= 0) continue;
                        if (!AurasById.TryGetValue(a.cardId, out var list))
                        {
                            list = new List<Aura>();
                            AurasById[a.cardId] = list;
                        }

                        list.Add(a);
                    }
                }

                if (dto?.directAttacks != null)
                {
                    foreach (var d in dto.directAttacks)
                    {
                        if (d == null || d.cardId <= 0) continue;
                        if (!DirectsById.TryGetValue(d.cardId, out var list))
                        {
                            list = new List<DirectGrant>();
                            DirectsById[d.cardId] = list;
                        }

                        list.Add(d);
                    }
                }

                if (dto?.extraAttacks != null)
                {
                    foreach (var e in dto.extraAttacks)
                    {
                        if (e == null || e.cardId <= 0) continue;
                        if (!ExtraById.TryGetValue(e.cardId, out var list))
                        {
                            list = new List<ExtraAttackGrant>();
                            ExtraById[e.cardId] = list;
                        }

                        list.Add(e);
                    }
                }

                AuraCardCount = AurasById.Count;
                DirectCardCount = DirectsById.Count;
                ExtraAttackCardCount = ExtraById.Count;
                Debug.Log(
                    $"[WRLDZ] YGOPro continuous catalog: {AuraCardCount} aura cards, " +
                    $"{DirectCardCount} direct-attack, {ExtraAttackCardCount} extra-attack " +
                    $"(from {dto?.scriptFiles ?? 0} Lua files).");
            }
            catch (Exception ex)
            {
                Debug.LogWarning("[WRLDZ] YGOPro continuous seed parse failed: " + ex.Message);
            }
        }

        public static IReadOnlyList<Aura> AurasFor(int cardId)
        {
            EnsureLoaded();
            return AurasById.TryGetValue(cardId, out var list) ? list : Array.Empty<Aura>();
        }

        public static bool HasAurasInZone(int cardId, string zone)
        {
            foreach (var a in AurasFor(cardId))
            {
                if (a == null) continue;
                if (string.IsNullOrEmpty(zone) ||
                    string.Equals(a.sourceZone, zone, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            return false;
        }

        public static IReadOnlyList<DirectGrant> DirectsFor(int cardId)
        {
            EnsureLoaded();
            return DirectsById.TryGetValue(cardId, out var list) ? list : Array.Empty<DirectGrant>();
        }

        public static bool GrantsDirectAttack(DuelEngine engine, CardInstance attacker)
        {
            if (engine == null || attacker == null) return false;
            foreach (var g in DirectsFor(attacker.CardId))
            {
                if (g == null) continue;
                if (string.IsNullOrEmpty(g.requiresName))
                    return true;
                if (FieldSpellEffects.NamedCardIsFaceUpOnField(engine, g.requiresName))
                    return true;
            }

            return false;
        }

        public static IReadOnlyList<ExtraAttackGrant> ExtraAttacksFor(int cardId)
        {
            EnsureLoaded();
            return ExtraById.TryGetValue(cardId, out var list) ? list : Array.Empty<ExtraAttackGrant>();
        }

        public static int[] ExtraAttackCardIds()
        {
            EnsureLoaded();
            var ids = new int[ExtraById.Count];
            ExtraById.Keys.CopyTo(ids, 0);
            return ids;
        }

        /// <summary>Max extra attacks granted (1 = two attacks this Battle Phase).</summary>
        public static int ExtraAttacks(DuelEngine engine, CardInstance attacker)
        {
            if (engine == null || attacker == null) return 0;
            var n = 0;
            foreach (var e in ExtraAttacksFor(attacker.CardId))
            {
                if (e == null) continue;
                if (!string.IsNullOrEmpty(e.requiresName) &&
                    !FieldSpellEffects.NamedCardIsFaceUpOnField(engine, e.requiresName))
                    continue;
                if (e.extra > n) n = e.extra;
            }

            return n;
        }
    }
}
